create table booking (id bigint generated by default as identity, status varchar(255), vehicle varchar(255), customer_id bigint, primary key (id))
create table customer (id bigint generated by default as identity, email varchar(120) not null, encrypted_password varchar(255) not null, first_name varchar(50) not null, last_name varchar(50) not null, primary key (id))
create table driver (id bigint generated by default as identity, age integer not null, date_of_expiry timestamp not null, first_name varchar(50) not null, last_name varchar(50) not null, licence_no varchar(50) not null, valid boolean not null, customer_id bigint not null, primary key (id))
create table employee (id bigint generated by default as identity, encrypted_password varchar(150) not null, first_name varchar(50) not null, last_name varchar(50) not null, username varchar(120) not null, primary key (id))
alter table booking add constraint UK_s1ex8m8o6u9g3859mnxewoa8p unique (vehicle)
alter table customer add constraint UK_dwk6cx0afu8bs9o4t536v1j5v unique (email)
alter table customer add constraint UK_giwiqkvk4x8vmw4nnu1wn3ptk unique (encrypted_password)
alter table booking add constraint FKlnnelfsha11xmo2ndjq66fvro foreign key (customer_id) references customer
alter table driver add constraint FKcsglflixk9q7txj6okcjn878k foreign key (customer_id) references customer
create table booking (id bigint generated by default as identity, status varchar(255), vehicle varchar(255), customer_id bigint, primary key (id))
create table customer (id bigint generated by default as identity, email varchar(120) not null, encrypted_password varchar(255) not null, first_name varchar(50) not null, last_name varchar(50) not null, primary key (id))
create table driver (id bigint generated by default as identity, age integer not null, date_of_expiry timestamp not null, first_name varchar(50) not null, last_name varchar(50) not null, licence_no varchar(50) not null, valid boolean not null, customer_id bigint not null, primary key (id))
create table employee (id bigint generated by default as identity, encrypted_password varchar(150) not null, first_name varchar(50) not null, last_name varchar(50) not null, username varchar(120) not null, primary key (id))
alter table booking add constraint UK_s1ex8m8o6u9g3859mnxewoa8p unique (vehicle)
alter table customer add constraint UK_dwk6cx0afu8bs9o4t536v1j5v unique (email)
alter table customer add constraint UK_giwiqkvk4x8vmw4nnu1wn3ptk unique (encrypted_password)
alter table booking add constraint FKlnnelfsha11xmo2ndjq66fvro foreign key (customer_id) references customer
alter table driver add constraint FKcsglflixk9q7txj6okcjn878k foreign key (customer_id) references customer
